export const pagesRoutes = [
  ["v-184f4da6","/intro.html",{"e":"<h1> 介绍页</h1>\n<p>将你的个人介绍和档案放置在此处。</p>\n","y":"a","title":"介绍页","i":"info"},["/intro","/intro.md"]],
  ["v-8daa1a0e","/",{"y":"h","title":"主页","i":"home"},["/index.html","/README.md"]],
  ["v-2e3eac9e","/slides.html",{"e":"<!-- markdownlint-disable MD024 MD033 MD051 -->\n","y":"s","title":"幻灯片页","i":"slides"},["/slides","/slides.md"]],
  ["v-4e65ec78","/demo/disable.html",{"c":["使用指南"],"g":["禁用"],"e":"<p>你可以通过设置页面的 Frontmatter，在页面禁用功能与布局。</p>\n","y":"a","title":"布局与功能禁用","i":"config"},["/demo/disable","/demo/disable.md"]],
  ["v-c151bf32","/demo/encrypt.html",{"c":["使用指南"],"g":["文章加密"],"n":true,"y":"a","title":"密码加密的文章","i":"lock"},["/demo/encrypt","/demo/encrypt.md"]],
  ["v-438ffe52","/demo/markdown.html",{"c":["使用指南"],"g":["Markdown"],"e":"<p>VuePress 主要从 Markdown 文件生成页面。因此，你可以使用它轻松生成文档或博客站点。</p>\n<p>你应该创建和编写 Markdown 文件，以便 VuePress 可以根据文件结构将它们转换为不同的页面。</p>\n","y":"a","title":"Markdown 展示","i":"markdown"},["/demo/markdown","/demo/markdown.md"]],
  ["v-6e19edb7","/demo/page.html",{"a":"Ms.Hope","d":"2020-01-01T00:00:00.000Z","l":"2020年1月1日","c":["使用指南"],"g":["页面配置","使用指南"],"u":true,"e":"<p><code>more</code> 注释之前的内容被视为文章摘要。</p>\n","y":"a","title":"页面配置","i":"page"},["/demo/page","/demo/page.md"]],
  ["v-1473bf53","/demo/",{"c":["使用指南"],"e":"<h2> 目录</h2>\n<ul>\n<li>\n<p><a href=\"/demo/markdown.html\" target=\"blank\">Markdown 展示</a></p>\n</li>\n<li>\n<p><a href=\"/demo/page.html\" target=\"blank\">页面展示</a></p>\n</li>\n<li>\n<p><a href=\"/demo/disable.html\" target=\"blank\">禁用展示</a></p>\n</li>\n<li>\n<p><a href=\"/demo/encrypt.html\" target=\"blank\">加密展示</a></p>\n</li>\n</ul>","y":"a","title":"主要功能与配置演示","i":"discover"},["/demo/index.html","/demo/README.md"]],
  ["v-6a278876","/md/interview/x-interview-1.html",{"d":"2022-01-18T00:00:00.000Z","l":"2022年1月18日","c":["面试题"],"e":"<p><code>more</code> Java全栈面试题总结（持续更新）。</p>\n","y":"a","title":"Java 全栈面试题汇总","i":"article"},["/md/interview/x-interview-1","/md/interview/x-interview-1.md"]],
  ["v-f08387ee","/md/spring/spring.html",{"d":"2022-01-17T00:00:00.000Z","l":"2022年1月17日","c":["Spring"],"e":"<p><code>more</code> 本文章主要介绍Spring框架整体架构，Spring的核心IOC，AOP的案例和具体实现机制；以及SpringMVC框架的案例和实现机制。</p>\n","y":"a","title":"Spring","i":"leaf"},["/md/spring/spring","/md/spring/spring.md"]],
  ["v-141d7897","/md/framework/orm-mybatis/mybatis-overview.html",{"d":"2022-01-18T00:00:00.000Z","l":"2022年1月18日","c":["Framework"],"e":"<p><code>more</code> Mybatis知识体系。</p>\n","y":"a","title":"Mybatis","i":"edit"},["/md/framework/orm-mybatis/mybatis-overview","/md/framework/orm-mybatis/mybatis-overview.md"]],
  ["v-41d63b3b","/md/java/basic/java-basic-lan.html",{"d":"2022-01-17T00:00:00.000Z","l":"2022年1月17日","c":["Java"],"e":"<h1> Java 面向对象</h1>\n","y":"a","title":"Java 面向对象","i":"java"},["/md/java/basic/java-basic-lan","/md/java/basic/java-basic-lan.md"]],
  ["v-617ab0a4","/md/java/basic/java-basic-oop.html",{"d":"2022-01-17T00:00:00.000Z","l":"2022年1月17日","c":["Java"],"e":"<h1> Java 基础知识</h1>\n","y":"a","title":"Java 基础知识","i":"java"},["/md/java/basic/java-basic-oop","/md/java/basic/java-basic-oop.md"]],
  ["v-3f0b1149","/md/db/nosql-redis/sql-redis-overview.html",{"d":"2022-01-17T00:00:00.000Z","l":"2022年1月17日","c":["数据库"],"e":"<h1> Redis数据库</h1>\n","y":"a","title":"Redis数据库","i":"mysql"},["/md/db/nosql-redis/sql-redis-overview","/md/db/nosql-redis/sql-redis-overview.md"]],
  ["v-0d233a93","/md/java/collection/java-collection.html",{"d":"2022-01-17T00:00:00.000Z","l":"2022年1月17日","c":["Java"],"e":"<h1> Java 集合框架</h1>\n","y":"a","title":"Java 集合框架","i":"java"},["/md/java/collection/java-collection","/md/java/collection/java-collection.md"]],
  ["v-69d731e9","/md/db/sql/sql-db.html",{"d":"2022-01-17T00:00:00.000Z","l":"2022年1月17日","c":["数据库"],"e":"<h1> 数据库原理</h1>\n","y":"a","title":"数据库原理","i":"mysql"},["/md/db/sql/sql-db","/md/db/sql/sql-db.md"]],
  ["v-4531b1d2","/md/db/sql/sql-lan.html",{"d":"2022-01-17T00:00:00.000Z","l":"2022年1月17日","c":["数据库"],"e":"<h1> SQL 语言</h1>\n","y":"a","title":"SQL 语言","i":"mysql"},["/md/db/sql/sql-lan","/md/db/sql/sql-lan.md"]],
  ["v-432c8f78","/md/db/sql-mysql/sql-mysql-overview.html",{"d":"2022-01-17T00:00:00.000Z","l":"2022年1月17日","c":["数据库"],"e":"<h1> MySQL 数据库</h1>\n","y":"a","title":"MySQL 数据库","i":"mysql"},["/md/db/sql-mysql/sql-mysql-overview","/md/db/sql-mysql/sql-mysql-overview.md"]],
  ["v-3706649a","/404.html",{"y":"p","title":""},["/404"]],
  ["v-49a01026","/md/interview/",{"y":"p","title":"Interview"},["/md/interview/index.html"]],
  ["v-2d0aa3df","/md/",{"y":"p","title":"Md"},["/md/index.html"]],
  ["v-59715303","/md/spring/",{"y":"p","title":"Spring"},["/md/spring/index.html"]],
  ["v-4b13e162","/md/framework/orm-mybatis/",{"y":"p","title":"Orm Mybatis"},["/md/framework/orm-mybatis/index.html"]],
  ["v-2ac2e710","/md/framework/",{"y":"p","title":"Framework"},["/md/framework/index.html"]],
  ["v-4630290f","/md/java/basic/",{"y":"p","title":"Basic"},["/md/java/basic/index.html"]],
  ["v-11af89ce","/md/java/",{"y":"p","title":"Java"},["/md/java/index.html"]],
  ["v-e9b4b0b4","/md/db/nosql-redis/",{"y":"p","title":"Nosql Redis"},["/md/db/nosql-redis/index.html"]],
  ["v-ed95419c","/md/db/",{"y":"p","title":"Db"},["/md/db/index.html"]],
  ["v-0be40ec3","/md/java/collection/",{"y":"p","title":"Collection"},["/md/java/collection/index.html"]],
  ["v-24647253","/md/db/sql/",{"y":"p","title":"Sql"},["/md/db/sql/index.html"]],
  ["v-4d7f055e","/md/db/sql-mysql/",{"y":"p","title":"Sql Mysql"},["/md/db/sql-mysql/index.html"]],
  ["v-5bc93818","/category/",{"y":"p","title":"分类"},["/category/index.html"]],
  ["v-744d024e","/tag/",{"y":"p","title":"标签"},["/tag/index.html"]],
  ["v-e52c881c","/article/",{"y":"p","title":"文章"},["/article/index.html"]],
  ["v-154dc4c4","/star/",{"y":"p","title":"收藏"},["/star/index.html"]],
  ["v-01560935","/timeline/",{"y":"p","title":"时间轴"},["/timeline/index.html"]],
  ["v-03d57386","/category/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/",{"y":"p","title":"使用指南 分类"},["/category/使用指南/","/category/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/index.html"]],
  ["v-83e1f92e","/tag/%E7%A6%81%E7%94%A8/",{"y":"p","title":"禁用 标签"},["/tag/禁用/","/tag/%E7%A6%81%E7%94%A8/index.html"]],
  ["v-1e143c90","/category/%E9%9D%A2%E8%AF%95%E9%A2%98/",{"y":"p","title":"面试题 分类"},["/category/面试题/","/category/%E9%9D%A2%E8%AF%95%E9%A2%98/index.html"]],
  ["v-1e447d61","/tag/%E6%96%87%E7%AB%A0%E5%8A%A0%E5%AF%86/",{"y":"p","title":"文章加密 标签"},["/tag/文章加密/","/tag/%E6%96%87%E7%AB%A0%E5%8A%A0%E5%AF%86/index.html"]],
  ["v-08073caa","/category/spring/",{"y":"p","title":"Spring 分类"},["/category/spring/index.html"]],
  ["v-484552dc","/tag/markdown/",{"y":"p","title":"Markdown 标签"},["/tag/markdown/index.html"]],
  ["v-3b776fee","/category/framework/",{"y":"p","title":"Framework 分类"},["/category/framework/index.html"]],
  ["v-a378ad66","/tag/%E9%A1%B5%E9%9D%A2%E9%85%8D%E7%BD%AE/",{"y":"p","title":"页面配置 标签"},["/tag/页面配置/","/tag/%E9%A1%B5%E9%9D%A2%E9%85%8D%E7%BD%AE/index.html"]],
  ["v-5831b135","/category/java/",{"y":"p","title":"Java 分类"},["/category/java/index.html"]],
  ["v-7b167472","/tag/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/",{"y":"p","title":"使用指南 标签"},["/tag/使用指南/","/tag/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/index.html"]],
  ["v-5e0b61bd","/category/%E6%95%B0%E6%8D%AE%E5%BA%93/",{"y":"p","title":"数据库 分类"},["/category/数据库/","/category/%E6%95%B0%E6%8D%AE%E5%BA%93/index.html"]],
]
